### ISSUE TITLE
The change from RPi.GPIO to pigpio did change the pin ID

### ISSUE THREAD

**Issue by brackendawson** [brackendawson/MFRC522-python#2]
And I should just use the /sys/class/gpio/\* files.

**Comment by benjie** [comment]
pigpio identifies pins by their broadcom number. RPi.GPIO can [do the same](http://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/) if you issue

```
GPIO.setmode(GPIO.BCM)
```

**Comment by brackendawson** [comment]
I know.

Also I think pigpio is pretty pointless (extra deamon running as root or with kmem), when all the script needs is to be in the gpio group.

**Comment by brackendawson** [comment]
Closing as I started using /sys/class/gpio
